spring:
  application:
    name: advanced-search
  datasource:
    password: ''
    url: jdbc:postgresql://localhost:5432/decagon
    username: ''
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true